services:
  maps-mongodb:
    image: bitnami/mongodb:latest
    container_name: maps-mongodb
    restart: always
    env_file:
      - .env.docker
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  maps-postgres:
    image: bitnami/postgresql:latest
    container_name: maps-postgres
    restart: always
    env_file:
      - .env.docker
    ports:
      - 5432:5432

volumes:
  mongo_data:
    driver: local
